name: layers
on:
  push:
    paths:
      - 'layers/**'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: set credentials
        run: |
          aws configure set region ap-northeast-2
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws --profile deptno configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws --profile deptno configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: deploy
        run: |
          cd layers
          terraform init
          terraform plan --out tfplan
          terraform apply tfplan
          cd -
